---
# tasks file for helm
- name: Install repo key
  ansible.builtin.shell: 'curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null'

- name: Set up repo
  ansible.builtin.shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list'

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - helm
    state: present
    update_cache: yes