version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8111:8111"
    volumes:
      - /teamcity_data:/data/teamcity_server/datadir
      - /var/log/teamcity:/opt/teamcity/logs
