---
# tasks file for teamcity
- name: Install pip
  ansible.builtin.apt:
    name: "python3-pip"
    state: present
    update_cache: true

- name: Install requests module
  ansible.builtin.pip:
    name:
      - requests
    state: present

- name: Create teamcity directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nkom
    group: nkom
    mode: "757"
  loop:
    - /opt/teamcity_data
    - /opt/teamcity_logs
    
- name: Start teamcity server container
  community.docker.docker_container:
    name: teamcity-server
    image: jetbrains/teamcity-server
    user: tcuser
    state: started
    ports:
     - "8111:8111"
    volumes:
      - "/opt/teamcity_data:/data/teamcity_server/datadir"
      - "/opt/teamcity_logs:/opt/teamcity/logs"
