---
# tasks file for k8s_client
- name: Install pip
  ansible.builtin.apt:
    name: "python3-pip"
    state: present
    update_cache: true

- name: Install kubernetes module
  ansible.builtin.pip:
    name:
      - kubernetes
    state: present

- name: Install kubectl
  community.general.snap:
    name: kubectl
    classic: yes
    state: present

- name: Install helm
  community.general.snap:
    name: helm
    classic: yes
    state: present

- name: Create directories for kubectl config
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nkom
    group: nkom
    mode: "755"
  with_items:
    - "/home/nkom/.minikube/profiles/minikube"
    - "/home/nkom/.kube"
  
- name: Copy kubectl settings from k8s server to local
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ item }}"
    private_key: /tmp/.id_rsa
  with_items:
    - "/home/nkom/.minikube/profiles/minikube/client.crt"
    - "/home/nkom/.minikube/profiles/minikube/client.key"
    - "/home/nkom/.minikube/ca.crt"
    - "/home/nkom/.kube/config"
  delegate_to: app-1

- name: Set k8s server in kubectl config
  ansible.builtin.lineinfile:
    path: "/home/nkom/.kube/config"
    regexp: '.*server:'
    line: '    server: {{ item }}'
    owner: nkom
    group: nkom
    mode: '0600'
  with_items:
    -  http://{{ hostvars['app-1']['ansible_eth0']['ipv4']['address'] }}:8001

- name: Copy monitoring manifests
  ansible.builtin.copy:
    src: monitoring
    dest: /usr/bin
    owner: nkom
    group: nkom
    mode: "700" 

- name: Apply manifests
  ansible.builtin.k8s:
    kubeconfig: /home/nkom/.kube/config
    src: "{{ obj_def_path}}/{{ item }}"
    state: present
    apply: true
  loop: "{{ obj_def_list }}"
  
