---
- name: Set up service users on all hosts
  hosts: all
  roles:
    - users

- name: Install docker and k8s on app hosts
  hosts: app-*
  roles:
    - docker
    - k8s

- name: Install kubectl and helm on dev hosts
  hosts: dev-*
  roles:
    - docker
    - k8s_client
    - teamcity