---
- name: Set up service users on all hosts
  hosts: all
  roles:
    - users

- name: Set up app hosts
  hosts: 
    - app-*
  roles:
    - docker
    - k8s

- name: Set up dev hosts
  hosts: dev-*
  roles:
    - docker
    - k8s_client
    - teamcity
    - teamcity_agent

- name: Set up prom hosts
  hosts: prom-*
  roles:
    - docker
    - esk
